/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardBody: typeof import('./src/components/inspiraUI/Card3D/CardBody.vue')['default']
    CardContainer: typeof import('./src/components/inspiraUI/Card3D/CardContainer.vue')['default']
    CardItem: typeof import('./src/components/inspiraUI/Card3D/CardItem.vue')['default']
    FallingStarsBg: typeof import('./src/components/inspiraUI/FallingStarsBg.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HoverShow: typeof import('./src/components/HoverShow.vue')['default']
    MediaMenu: typeof import('./src/components/MediaMenu.vue')['default']
    MyIcon: typeof import('./src/components/My-Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
