/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HoverShow: typeof import('./components/HoverShow.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    MediaMenu: typeof import('./components/MediaMenu.vue')['default']
    MyIcon: typeof import('./components/My-Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
